title: jw53111 Memory Garden
description: JW Wang's Personal Blog
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      jekyll-theme-WuK:
        comments:
          append: |
            <div id="utterances_thread"></div>
            <script src="https://utteranc.es/client.js"
              repo="JW53111/jw53111.github.io"
              issue-term="url"
              label="Comment"
              theme="preferred_color_scheme"
              lang="en"
              crossorigin="anonymous"
              async>
            </script>
        default:
          html_lang: zh
          color-mode: auto
          light-theme: light
          dark-theme: dark
          style: /assets/css/style.css
          menu:
            nav:
              - title: '首页 / Index'
                href: /
              - title: '留言 / Comments'
                href: /comments/
              - title: '归档 / Archive'
                href: /archive/
              - title: '标签 / Tags'
                href: /tags/
              - title: '简历 / Resume'
                href: /resume/
              - title: 'GitHub'
                href: https://github.com/JW53111
            footer: |
              <div>
                <span id="busuanzi_container_site_pv">
                  <span id="busuanzi_value_site_pv"></span> visits
                </span>
                <span id="busuanzi_container_site_uv">
                  <span id="busuanzi_value_site_uv"></span> vistors
                </span>
                <script src="https://cdn.jsdelivr.net/npm/busuanzi@2.3/bsz.pure.mini.js" async></script>
              </div>
              <div>
                (C) {{ 2025 }} Jiawu
              </div>
          prepend:
            - |
              <form class="SelectMenu-filter">
                <input
                  class="SelectMenu-input form-control"
                  type="text"
                  placeholder="Search"
                  aria-label="Filter"
                  id="wrap-search-input"
                />
                <ol class="px-5" id="wrap-search-result"></ol>
                <script
                  src="https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.10.0/dest/simple-jekyll-search.min.js"
                  async
                  onload='
                    SimpleJekyllSearch({
                      json: "/assets/simple-jekyll-search/search.json",
                      searchInput: document.getElementById("wrap-search-input"),
                      resultsContainer: document.getElementById("wrap-search-result"),
                      searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                      limit: 9
                    })'
                ></script>
              </form>
          append_to_head:
            - |
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@primer/css@22.0.2/dist/primer.min.css" />
              <link rel="stylesheet" href="/assets/css/style.css" />
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pygments-rouge-css@0.1.0/perldoc.min.css" />
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/monaspace-xenon@5.2.5/index.min.css" />
              <link rel='stylesheet' href='https://chinese-fonts-cdn.deno.dev/packages/jyhpws/dist/%E6%9E%81%E5%BD%B1%E6%AF%81%E7%89%87%E6%96%87%E5%AE%8B/result.css' />
          post:
            date:
              enable: true
              prepend: post on
            wordcount:
              enable: true
              prepend: about
              unit: words
            readtime:
              enable: true
              prepend: require
              unit: min
              divided_by: 300
            copyright: |
              <a target="_blank" href="https://creativecommons.org/licenses/by/4.0/deed.zh" rel="license">CC BY 4.0</a>（除特别声明或转载文章外）
            related_posts:
              enable: true

plugins:
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@5.5.0

readme_index:
  with_frontmatter: true

permalink: pretty
timezone: Asia/Shanghai
future: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      disable: false
      line_numbers: true
    span:
      disable: false

# 以下为 githubpage上不可修改的参数，见<https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>
#lsi: false # 为相关文章生成索引
#safe: true # 禁用自定义插件
#source: [your repo's top level directory] # Jekyll 读取文件的路径
#incremental: false # 增量生成
#highlighter: rouge # 代码高亮器
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
