# =========================================
# 基本站点信息
# =========================================
title: jw53111 Home # 站点标题
description: JW Wang's Personal Blog
baseurl: ""  # 如果博客在根目录下保持空，建在子目录请加目录名
timezone: Asia/Shanghai # 时区
permalink: pretty # 美化 URL
future: true # 允许发布未来时间文章

# =========================================
# 默认配置
# =========================================
defaults:
  - scope:
      path: "" # 空字符串表示全局作用
    values:
      jekyll-theme-WuK:
        default:
          html_lang: zh # 默认中文
          color-mode: auto # 自动切换浅色/深色
          light-theme: light
          dark-theme: dark
          menu:
            nav:
              - title: '首页 / Index'
                href: /
              - title: '留言 / Comments'
                href: /comments/
              - title: '归档 / Archive'
                href: /archive/
              - title: '标签 / Tags'
                href: /tags/
              - title: '捐赠 / Donate'
                href: /donate/
              - title: '简历 / Resume'
                href: https://resume.wu-kan.cn/
              - title: 'GitHub'
                href: https://github.com/JW53111
              - title: '语言 / Language' 
                href: '#'  # 新增语言切换按钮，占位，下面用 JS 自动切换
          comments:
            append: |
              <div class="giscus">
                Loading comments...
              </div>
              <script src="https://giscus.app/client.js"
                data-repo="JW53111/jw53111.github.io" # 改成你的仓库
                data-repo-id="你的repo-id"
                data-category="Announcements"
                data-category-id="你的category-id"
                data-mapping="url"
                data-strict="0"
                data-reactions-enabled="1"
                data-emit-metadata="0"
                data-input-position="top"
                data-theme="preferred_color_scheme"
                data-lang="en"
                crossorigin="anonymous"
                async>
              </script>

# =========================================
# 页面 & 文章插件配置
# =========================================
plugins:
  - jekyll-readme-index  # 使用 README 做 index
  - jekyll-default-layout # 自动生成 layout
  - jekyll-seo-tag # 页面 SEO
  - jekyll-sitemap # 站点地图
  - jekyll-feed # RSS feed
  - jekyll-redirect-from # 页面重定向
  - jekyll-paginate # 分页
  - jekyll-remote-theme # 使用远程主题

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@5.5.0 # 固定版本防止更新破坏布局

# =========================================
# 页面默认配置
# =========================================
page:
  title:
    enable: true # 自动生成 H1 title
  prepend:
    - |
      <style>
        .markdown-body p { text-indent: 2em; } 
        .markdown-body img { max-width: calc(100% - 4em); }
      </style>
  plugin:
    - smart_include:
        enable: true
        key: $
      append: |
        <!-- KaTeX 数学公式渲染 -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css"/>
        <style>.katex-display>.katex {white-space: normal;}</style>
        <script src="https://cdn.jsdelivr.net/combine/npm/katex@0.16.22/dist/katex.min.js,npm/katex@0.16.22/dist/contrib/auto-render.min.js"
          async="async"
          onload='renderMathInElement(document.body, { delimiters: [{left: "$$", right: "$$", display: true},{ left: "$", right: "$", display: false }]})'>
        </script>

# =========================================
# 文章默认配置
# =========================================
post:
  date:
    enable: true
    prepend: post on
  wordcount:
    enable: true
    prepend: about
    unit: words
  readtime:
    enable: true
    prepend: require
    unit: min
    divided_by: 300
  copyright: |
    <!-- 使用 CC BY 4.0 知识共享协议 -->
    <a target="_blank" href="https://creativecommons.org/licenses/by/4.0/deed.zh" rel="license">
      CC BY 4.0
    </a>

# =========================================
# HTML 压缩配置
# =========================================
compress_html:
  clippings: all
  comments: []
  endings: all
  ignore:
    envs: all
  blanklines: false
  profile: false
  startings: []

# =========================================
# Markdown 配置
# =========================================
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      disable: false
      line_numbers: true
    span:
      disable: false

# =========================================
# 双语言切换 JS
# =========================================
prepend_to_head:
  - |
    <script>
      document.addEventListener("DOMContentLoaded", function(){
        let navLang = document.querySelector('a[href="#"]');
        if(navLang){
          // 根据路径判断是英文页面还是中文页面
          navLang.textContent = location.pathname.startsWith('/en/') ? '中文 / Chinese' : 'English / 英文';
          navLang.href = location.pathname.startsWith('/en/') ? '/' : '/en/';
        }
      });
    </script>
